package Net::Swirl::CurlEasy::Info {

  use warnings;
  use 5.020;

  # ABSTRACCT: Private class for Net::Swirl::CurlEasy

  # NOTE: This document is autogenerated from the template
  # maint/tt/Info.pm.tt
  # Please see maint/README.md for details on updating.

=head1 SYNOPSIS

 $ perldoc Net::Swirl::CurlEasy

=head1 DESCRIPTION

This is a private class for L<Net::Swirl::CurlEasy> see the main documentation for the public interface.

=cut

  package Net::Swirl::CurlEasy {
    our %info = (%info,
      effective_url => [ 1048577, \&_getinfo_string ],
      response_code => [ 2097154, \&_getinfo_long ],
      total_time => [ 3145731, \&_getinfo_double ],
      namelookup_time => [ 3145732, \&_getinfo_double ],
      connect_time => [ 3145733, \&_getinfo_double ],
      pretransfer_time => [ 3145734, \&_getinfo_double ],
      size_upload => [ 3145735, \&_getinfo_double ],
      size_upload_t => [ 6291463, \&_getinfo_off_t ],
      size_download => [ 3145736, \&_getinfo_double ],
      size_download_t => [ 6291464, \&_getinfo_off_t ],
      speed_download => [ 3145737, \&_getinfo_double ],
      speed_download_t => [ 6291465, \&_getinfo_off_t ],
      speed_upload => [ 3145738, \&_getinfo_double ],
      speed_upload_t => [ 6291466, \&_getinfo_off_t ],
      header_size => [ 2097163, \&_getinfo_long ],
      request_size => [ 2097164, \&_getinfo_long ],
      ssl_verifyresult => [ 2097165, \&_getinfo_long ],
      filetime => [ 2097166, \&_getinfo_long ],
      filetime_t => [ 6291470, \&_getinfo_off_t ],
      content_length_download => [ 3145743, \&_getinfo_double ],
      content_length_download_t => [ 6291471, \&_getinfo_off_t ],
      content_length_upload => [ 3145744, \&_getinfo_double ],
      content_length_upload_t => [ 6291472, \&_getinfo_off_t ],
      starttransfer_time => [ 3145745, \&_getinfo_double ],
      content_type => [ 1048594, \&_getinfo_string ],
      redirect_time => [ 3145747, \&_getinfo_double ],
      redirect_count => [ 2097172, \&_getinfo_long ],
      private => [ 1048597, \&_getinfo_string ],
      http_connectcode => [ 2097174, \&_getinfo_long ],
      httpauth_avail => [ 2097175, \&_getinfo_long ],
      proxyauth_avail => [ 2097176, \&_getinfo_long ],
      os_errno => [ 2097177, \&_getinfo_long ],
      num_connects => [ 2097178, \&_getinfo_long ],
      lastsocket => [ 2097181, \&_getinfo_long ],
      ftp_entry_path => [ 1048606, \&_getinfo_string ],
      redirect_url => [ 1048607, \&_getinfo_string ],
      primary_ip => [ 1048608, \&_getinfo_string ],
      appconnect_time => [ 3145761, \&_getinfo_double ],
      condition_unmet => [ 2097187, \&_getinfo_long ],
      rtsp_session_id => [ 1048612, \&_getinfo_string ],
      rtsp_client_cseq => [ 2097189, \&_getinfo_long ],
      rtsp_server_cseq => [ 2097190, \&_getinfo_long ],
      rtsp_cseq_recv => [ 2097191, \&_getinfo_long ],
      primary_port => [ 2097192, \&_getinfo_long ],
      local_ip => [ 1048617, \&_getinfo_string ],
      local_port => [ 2097194, \&_getinfo_long ],
      http_version => [ 2097198, \&_getinfo_long ],
      proxy_ssl_verifyresult => [ 2097199, \&_getinfo_long ],
      protocol => [ 2097200, \&_getinfo_long ],
      scheme => [ 1048625, \&_getinfo_string ],
      total_time_t => [ 6291506, \&_getinfo_off_t ],
      namelookup_time_t => [ 6291507, \&_getinfo_off_t ],
      connect_time_t => [ 6291508, \&_getinfo_off_t ],
      pretransfer_time_t => [ 6291509, \&_getinfo_off_t ],
      starttransfer_time_t => [ 6291510, \&_getinfo_off_t ],
      redirect_time_t => [ 6291511, \&_getinfo_off_t ],
      appconnect_time_t => [ 6291512, \&_getinfo_off_t ],
      retry_after => [ 6291513, \&_getinfo_off_t ],
      effective_method => [ 1048634, \&_getinfo_string ],
      proxy_error => [ 2097211, \&_getinfo_long ],
      referer => [ 1048636, \&_getinfo_string ],
      cainfo => [ 1048637, \&_getinfo_string ],
      capath => [ 1048638, \&_getinfo_string ],
    );
  }
}

1;

__END__
