#!/bin/bash

set -ex

cip sudo apt-get update 
cip sudo apt-get install libcurl4-openssl-dev libffi-dev

if [[ "$CIP_ENV" =~ TEST_EXAMPLES ]]; then
  cip sudo apt-get install screen
  cip exec cpanm -n Plack::Component
fi
